#
# Role: geerlingguy.apache
# https://github.com/geerlingguy/ansible-role-apache
#
apache_listen_port: 80
apache_vhosts_filename: "local-mediawiki.conf"
apache_vhosts:
  - servername: "wiki.klenwell.localhost"
    documentroot: "/var/www/html"
