# roles/init/tasks/main.yml
---
- name: Create mediawiki directory
  file:
    path: "{{ installed_dir.mediawiki }}"
    state: directory

- name: Download Mediawiki and unzip
  unarchive:
    src: "{{ mediawiki_source }}"
    dest: "{{ devops_dir.downloads }}"
    remote_src: yes
    creates: "{{ devops_dir.downloads }}/mediawiki-{{ mediawiki_version }}"

# Recursive copy will not work until Ansible 2.8
#- name: Copy Mediawiki to webserver document root
#  copy:
#    src: "{{ devops_dir.downloads }}/mediawiki-{{ mediawiki_version }}"
#    dest: "{{ installed_dir.mediawiki }}"
#    remote_src: yes
- name: Copy Mediawiki to webserver document root (using command)
  shell: cp -r {{ devops_dir.downloads }}/mediawiki-{{ mediawiki_version }}/* {{ installed_dir.mediawiki }}

- name: Download GoogleLogin extension
  unarchive:
    src: https://extdist.wmflabs.org/dist/extensions/GoogleLogin-REL1_32-0b27530.tar.gz
    dest: "{{ devops_dir.downloads }}"
    remote_src: yes
    creates: "{{ devops_dir.downloads }}/GoogleLogin"

#- name: Copy GoogleLogin extension to webserver document root
#  copy:
#    src: "{{ devops_dir.downloads }}/GoogleLogin"
#    dest: "{{ installed_dir.mediawiki }}/extensions/GoogleLogin"
#    remote_src: yes
- name: Copy GoogleLogin extension to webserver document root (using command)
  shell: cp -r {{ devops_dir.downloads }}/GoogleLogin {{ installed_dir.mediawiki }}/extensions

- name: Runs Mediawiki install script
  shell: >
    php maintenance/install.php
    --dbserver="localhost"
    --dbname={{ wiki_db_name_user_pw }}
    --dbuser={{ wiki_db_name_user_pw }}
    --dbpass={{ wiki_db_name_user_pw }}
    --server="https://{{ wiki_domain }}"
    --scriptpath=/mediawiki
    --lang=en
    --pass={{ wiki_admin_pw }}
    --with-extensions
    "{{ wiki_name }}"
    "{{ wiki_admin_user }}"
  args:
    chdir: "{{ installed_dir.mediawiki }}"
    creates: "{{ installed_dir.mediawiki }}/LocalSettings.php"
