#
# To run playbook:
#   ansible-playbook playbook.yml --ask-become-pass -v
#
# To run specific roles, add tag dev:
#   - { role: wiki, tags: dev }
# Then run playbook with --tags option:
#   ansible-playbook ansible-desktop.yml --ask-become-pass --tags dev -v
#
# Source: https://github.com/Benoth/ansible-ubuntu/blob/1786382/ansible-desktop.yml
#
---
- name: Set up Mediawiki wiki locally
  hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
